### ISSUE TITLE
How to run my own dataset?

### ISSUE THREAD

**Issue by HquGhy** [likojack/bnv_fusion#11]
How to run my own dataset?

**Comment by likojack** [comment]
You can use the [dataset for ARKit](https://github.com/likojack/bnv_fusion/blob/17a64d7ba8a74946ff826e0603c5ff7827196a70/src/datasets/fusion_inference_dataset.py#L241) as a template for data loading.

**Comment by HquGhy** [comment]
Is it necessary to have a coarse-precision model in  myself data set?

`rough_mesh_path = os.path.join(self.seq_dir, "export.obj")`

**Comment by likojack** [comment]
We use this to determine the 3D dimensions of a scene. You can also set them manually if you know the dimensions.
