### ISSUE TITLE
ERROR while using 3D scanner data

### ISSUE THREAD

**Issue by feiqiu-cyber** [likojack/bnv_fusion#12]
I get error
![image](https://user-images.githubusercontent.com/79258566/215256147-9a0494e8-96e9-4c56-97ef-d9bda0cadac1.png)
And I print the active_buf_indices
![image](https://user-images.githubusercontent.com/79258566/215256196-6b39cdbc-8e9b-49a2-8dd7-4f6034f0916e.png)
I got:
![image](https://user-images.githubusercontent.com/79258566/215256216-6832d144-a8ce-4013-b356-3bcac427219b.png)
Does the error comes from  open3d version? but i change the open3d version == 0.14.1 ,the error still exists

**Comment by vadim-v-lebedev** [comment]
I've got the same error message. What was the solution?

**Comment by JyotiLuxolis** [comment]
Hello @vadim-v-lebedev  @feiqiu-cyber. Were you able to fix this error?
