### ISSUE TITLE
the ground truth mesh for 3dscene seems cut in come cube

### ISSUE THREAD

**Issue by Jarrome** [likojack/bnv_fusion#14]
I compared with ScanNet that looks fair.

But for 3Dscene (just find, not check ICL yet), the mesh seems trimed. See the sharp cut line on the floor.

![Screenshot from 2023-03-13 21-56-50](https://user-images.githubusercontent.com/13412144/224830591-b8cdc735-4512-4a74-8bf8-dd30b2d20a24.png)

While mine  result has a lot more,
![Screenshot from 2023-03-13 21-59-35](https://user-images.githubusercontent.com/13412144/224831116-affbd3b6-d792-4986-a026-dd1eaf043f02.png)

This cause around 68 acc which is quite close to DI-Fusion.

So I'm wondering if author also cut the DI-Fusion? Or DI-Fusion also use the same un-cutted for compare?

Otherwise, how can I cut my mesh to have a fair compare with bnv-fusion?

**Comment by likojack** [comment]
The GT mesh provided by the dataset is cut for some reason. We have to truncate the depth maps to 3m (see [here](https://github.com/likojack/bnv_fusion/blob/ad4de0b4666f308a22b680a249172f27059b5322/src/scripts/run_inference_on_scene3d.py#L20)) to match the GT mesh.

**Comment by Jarrome** [comment]
Emmm, I also use depth map truncated to 3m...
This does not explain the clean cut because you truncated on local frame...

I guess maybe because you use bound [-1,1]^3 ?

**Comment by likojack** [comment]
We truncated the extracted mesh based on the dimensions of the GT mesh, see [here](https://github.com/likojack/bnv_fusion/blob/7a2d0dcd65c186e5a38d733387999be82baf1ad4/src/scripts/run_rgbd_intergration.py#L100)

**Comment by Jarrome** [comment]
Ah, ok. Thanks for the help. :D
