### ISSUE TITLE
Unresolved reference 'Volume'

### ISSUE THREAD

**Issue by rancheng** [likojack/bnv_fusion#3]
The `Volume` here is not defined:

https://github.com/likojack/bnv_fusion/blob/9c8655a2da0c4601b16f558b6d98f2dea31cd528/src/datasets/fusion_dataset.py#L109-L111

Do you mean:

`TSDFVolume` ?

**Comment by likojack** [comment]
It should refer to [VolumeList](https://github.com/likojack/bnv_fusion/blob/main/src/models/sparse_volume.py). Could you please let me know what comand did you run?

**Comment by likojack** [comment]
close now due to inactivity
