### ISSUE TITLE
ICL_NUIM dataset from official site are not matched

### ISSUE THREAD

**Issue by Jarrome** [likojack/bnv_fusion#4]
Excellent work!

I attempt to play around with ICL_NUIM. But somehow your ```src/scripts/generate_fusion_data_icl_nuim.py``` do not match the data in ```https://www.doc.ic.ac.uk/~ahanda/VaFRIC/iclnuim.html```.

For example, the gt_mesh.ply, {RENDER_PATH}-color,  {RENDER_PATH}-depth-simulated, RENDER_PATH}-depth-clean. Where to get this. In addition, the scale is 1000, which is not compatible with ICL-NUIM.

Which format does this project use? The data I use is in TUM format.

**Comment by likojack** [comment]
We use the augmented ICL-NUIM from here: http://redwood-data.org/indoor/dataset.html.

**Comment by Jarrome** [comment]
Thank you, Kejie, for the very quick reply. 

I will now close this issue as the question is well solved.
