### ISSUE TITLE
I have the two question.

### ISSUE THREAD

**Issue by wr447329532** [likojack/bnv_fusion#7]
Hello, I have a questions for you:
     ModuleNotFoundError: No module named 'src'

**Comment by likojack** [comment]
Thanks for the feedback. I have updated the readme accordingly.

**Comment by wr447329532** [comment]
Thanks。Second question: Can you provide a docker image? anaconda installed many times the environment has been in conflict。

**Comment by likojack** [comment]
As mentioned in the readme, The docker image isn't working properly due to Open3D. Unfortunately I haven't got time to figure out a solution for that yet. If you can provide a dockerfile with pytorch and open3d installed, it would be superb!
