### ISSUE TITLE
Augmented ICL-NUIM intrinsics

### ISSUE THREAD

**Issue by Zzh2000** [likojack/bnv_fusion#8]
Hi, 
Thanks for the amazing work!

I just have one simple question regarding the Augmented ICL-NUIM dataset. I see in your code you set the fx fy to 525.0 https://github.com/likojack/bnv_fusion/blob/e1f3216442acf851f42695e6b294f7e14f307aff/src/scripts/generate_fusion_data_icl_nuim.py#L66, while in original ICL-NUIM dataset the fx and fy is 481.20 and 480.00 https://www.doc.ic.ac.uk/~ahanda/VaFRIC/codes.html. 
I wonder if there is some documentation for the augmented ICL-NUIM that leads to the change of intrinsics.

Thanks a lot!
Zihan

**Comment by likojack** [comment]
Hi Zihan,

It is indeed tricky to get these parameters. It also took me a while to find it again just now. Please see here: https://qianyi.info/scenedata.html#Format

The intrinsics are applicable to a few datasets that the authors built.

Cheers,
Kejie

**Comment by Zzh2000** [comment]
Hi Kejie,

Thank you for your assistance! It is really helpful! :)

Best,
Zihan
