### ISSUE TITLE
Question about interpolation in global-level fusion.

### ISSUE THREAD

**Issue by GostInShell** [likojack/bnv_fusion#9]
Hi! Thanks for contributing the code of your excellent work!

I have a question regarding the interpolation strategy in the volume rendering of global-level fusion. 
I notice that here the `alpha` is derived by first estimating the `alpha` at the corner points and then interpolating. This is different from recent works that first interpolate features, and then query the `alpha`. 
https://github.com/likojack/bnv_fusion/blob/17a64d7ba8a74946ff826e0603c5ff7827196a70/src/models/sparse_volume.py#L792

Does this strategy show better performance than the feature intepolation one? Are there any specific considerations?

**Comment by likojack** [comment]
We used corner points because each feature voxel is independent. We use the local coordinate rather than the global coordinate of the entire scene, which is different from some recent works.
